name: Gosec
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - name: Run Gosec
        uses: securego/gosec@master
        with:
          args: '-exclude=G104,G115,G304,G406,G507 -exclude-dir=builtin/gen ./...'