name: Test Trigger

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Internal CI
        uses: peter-evans/repository-dispatch@v3
#        if: ${{ inputs.trigger_internal_ci }}
        continue-on-error: true
        with:
          token: ${{ secrets.INTERNAL_CI_TOKEN }}
          repository: vechain/thor-internal-ci
          event-type: internal-thor-ci
          client-payload: '{"thor_image": "ghcr.io/vechain/thor:master-latest"}'
