name: E2E Tests

on:
  workflow_call:

jobs:
  build-docker-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: vechain/thor:${{ github.sha }}
          outputs: type=docker,dest=/tmp/vechain-thor.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vechain-thor-image-${{ github.sha }}
          path: /tmp/vechain-thor.tar
          retention-days: 7

  run-tests:
    runs-on: ubuntu-latest
    needs: build-docker-image
    env:
      THOR_IMAGE: vechain/thor:${{ github.sha }}
    name: Run Tests
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: vechain/thor-e2e-tests
          # https://github.com/vechain/thor-e2e-tests/tree/00bd3f1b949b05da94e82686e0089a11a136c34c
          ref: 00bd3f1b949b05da94e82686e0089a11a136c34c

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: vechain-thor-image-${{ github.sha }}
          path: /tmp

      - name: Setup Node JS
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Load image
        run: |
          docker load --input /tmp/vechain-thor.tar
          docker image ls -a

      - name: Run Tests
        run: |
          export THOR_IMAGE=vechain/thor:${{ github.sha }}
          yarn install
          yarn test

      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: e2e-test-results-${{ github.sha }}
          path: ./junit.xml
          retention-days: 14
